

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.*;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Ale
 */
public class Calcolatrice extends javax.swing.JFrame implements KeyListener {

    double operator_1, operator_2;
    boolean setupBrackets;
    int id_operation = -1;

    /*
     *
     * Creates new form Calcolatrice
     */
    
    public Calcolatrice() {
        this.addKeyListener(this);
        initComponents();
        
        operator_1 = operator_2 = 0;
        
        btn_9.setMnemonic( KeyEvent.VK_9 );
        btn_8.setMnemonic( KeyEvent.VK_8 );
        btn_7.setMnemonic( KeyEvent.VK_7 );
        btn_6.setMnemonic( KeyEvent.VK_6 );
        btn_5.setMnemonic( KeyEvent.VK_5 );
        btn_4.setMnemonic( KeyEvent.VK_4 );
        btn_3.setMnemonic( KeyEvent.VK_3 );
        btn_2.setMnemonic( KeyEvent.VK_2 );
        btn_1.setMnemonic( KeyEvent.VK_1 );
        btn_0.setMnemonic( KeyEvent.VK_0 );
        
        btn_add.setMnemonic( KeyEvent.VK_ADD );
        btn_div.setMnemonic( KeyEvent.VK_DIVIDE );
        btn_sub.setMnemonic( KeyEvent.VK_SUBTRACT );
        btn_mul.setMnemonic( KeyEvent.VK_MULTIPLY );
        
        
        setupBrackets = false;
        
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calcolatrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calcolatrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calcolatrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calcolatrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calcolatrice().setVisible(true);
            }
        });
    }
    
    @Override
    public void keyTyped(KeyEvent e) { }

    @Override
    public void keyPressed(KeyEvent e) { 
        int c = e.getKeyCode();
        if( c == KeyEvent.VK_7 ) {
            System.out.println("Test");
        }
    }

    @Override
    public void keyReleased(KeyEvent e) { }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        lbl_input = new javax.swing.JLabel();
        lbl_output = new javax.swing.JLabel();
        btn_7 = new javax.swing.JButton();
        btn_8 = new javax.swing.JButton();
        btn_9 = new javax.swing.JButton();
        btn_5 = new javax.swing.JButton();
        btn_6 = new javax.swing.JButton();
        btn_4 = new javax.swing.JButton();
        btn_1 = new javax.swing.JButton();
        btn_2 = new javax.swing.JButton();
        btn_3 = new javax.swing.JButton();
        btn_ce = new javax.swing.JButton();
        btn_0 = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        btn_sub = new javax.swing.JButton();
        btn_mul = new javax.swing.JButton();
        btn_div = new javax.swing.JButton();
        btn_res = new javax.swing.JButton();
        btn_comma = new javax.swing.JButton();
        btn_delChar = new javax.swing.JButton();
        btn_sin = new javax.swing.JButton();
        btn_cos = new javax.swing.JButton();
        btn_tan = new javax.swing.JButton();
        btn_quadrato = new javax.swing.JButton();
        btn_cubo = new javax.swing.JButton();
        btn_elevazione_n = new javax.swing.JButton();
        btn_elevation1 = new javax.swing.JButton();
        btn_rad = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        lbl_otherInfo = new javax.swing.JLabel();
        btn_mod = new javax.swing.JButton();
        btn_sqrt = new javax.swing.JButton();
        btn_brackets_open = new javax.swing.JButton();
        btn_brackets_close = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lbl_input.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_input.setForeground(new java.awt.Color(51, 51, 51));
        lbl_input.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        lbl_output.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl_output.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        btn_7.setText("7");
        btn_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_7ActionPerformed(evt);
            }
        });

        btn_8.setText("8");
        btn_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_8ActionPerformed(evt);
            }
        });

        btn_9.setText("9");
        btn_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_9ActionPerformed(evt);
            }
        });

        btn_5.setText("5");
        btn_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_5ActionPerformed(evt);
            }
        });

        btn_6.setText("6");
        btn_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_6ActionPerformed(evt);
            }
        });

        btn_4.setText("4");
        btn_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_4ActionPerformed(evt);
            }
        });

        btn_1.setText("1");
        btn_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_1ActionPerformed(evt);
            }
        });

        btn_2.setText("2");
        btn_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_2ActionPerformed(evt);
            }
        });

        btn_3.setText("3");
        btn_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_3ActionPerformed(evt);
            }
        });

        btn_ce.setBackground(new java.awt.Color(255, 0, 0));
        btn_ce.setText("CE");
        btn_ce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ceActionPerformed(evt);
            }
        });

        btn_0.setText("0");
        btn_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_0ActionPerformed(evt);
            }
        });

        btn_add.setText("+");
        btn_add.setMaximumSize(new java.awt.Dimension(39, 25));
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_sub.setText("-");
        btn_sub.setMaximumSize(new java.awt.Dimension(39, 25));
        btn_sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_subActionPerformed(evt);
            }
        });

        btn_mul.setText("*");
        btn_mul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mulActionPerformed(evt);
            }
        });

        btn_div.setText("/");
        btn_div.setToolTipText("");
        btn_div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_divActionPerformed(evt);
            }
        });

        btn_res.setBackground(new java.awt.Color(0, 153, 255));
        btn_res.setText("=");
        btn_res.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resActionPerformed(evt);
            }
        });

        btn_comma.setText(".");
        btn_comma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_commaActionPerformed(evt);
            }
        });

        btn_delChar.setBackground(new java.awt.Color(255, 102, 102));
        btn_delChar.setText("<-");
        btn_delChar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delCharActionPerformed(evt);
            }
        });

        btn_sin.setText("sin");
        btn_sin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sinActionPerformed(evt);
            }
        });

        btn_cos.setText("cos");
        btn_cos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cosActionPerformed(evt);
            }
        });

        btn_tan.setText("tan");
        btn_tan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tanActionPerformed(evt);
            }
        });

        btn_quadrato.setText("^2");
        btn_quadrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quadratoActionPerformed(evt);
            }
        });

        btn_cubo.setText("^3");
        btn_cubo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cuboActionPerformed(evt);
            }
        });

        btn_elevazione_n.setText("^n");
        btn_elevazione_n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_elevazione_nActionPerformed(evt);
            }
        });

        btn_elevation1.setText("1/x");
        btn_elevation1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_elevation1ActionPerformed(evt);
            }
        });

        btn_rad.setText("rad");
        btn_rad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_radActionPerformed(evt);
            }
        });

        lbl_otherInfo.setForeground(new java.awt.Color(153, 153, 153));
        lbl_otherInfo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        btn_mod.setText("%");
        btn_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modActionPerformed(evt);
            }
        });

        btn_sqrt.setText("√");
        btn_sqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sqrtActionPerformed(evt);
            }
        });

        btn_brackets_open.setText("(");
        btn_brackets_open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_brackets_openActionPerformed(evt);
            }
        });

        btn_brackets_close.setText(")");
        btn_brackets_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_brackets_closeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_otherInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_ce, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_delChar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_mul, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(172, 172, 172)
                                            .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(btn_1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(btn_2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(btn_0, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(btn_3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btn_comma, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(8, 8, 8)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(btn_div, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btn_res, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btn_4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btn_5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btn_6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(btn_sub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btn_sin, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btn_cos, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btn_tan, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btn_rad, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(btn_quadrato, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btn_cubo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btn_elevazione_n, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btn_elevation1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_sqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_brackets_open, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_brackets_close, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_output, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(lbl_input, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_input, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_output, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_otherInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_mul)
                            .addComponent(btn_ce)
                            .addComponent(btn_delChar)
                            .addComponent(btn_mod))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_7)
                            .addComponent(btn_8)
                            .addComponent(btn_9)
                            .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_4)
                            .addComponent(btn_5)
                            .addComponent(btn_6)
                            .addComponent(btn_sub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_sin)
                            .addComponent(btn_cos)
                            .addComponent(btn_tan)
                            .addComponent(btn_rad))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_quadrato)
                            .addComponent(btn_cubo)
                            .addComponent(btn_elevazione_n)
                            .addComponent(btn_elevation1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_sqrt)
                            .addComponent(btn_brackets_open)
                            .addComponent(btn_brackets_close))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_1)
                    .addComponent(btn_div)
                    .addComponent(btn_2)
                    .addComponent(btn_3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_res)
                    .addComponent(btn_0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_comma))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    
    private void btn_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_7ActionPerformed
       String txt = btn_7.getText();
       
       lbl_input.setText( lbl_input.getText() + txt );
    }//GEN-LAST:event_btn_7ActionPerformed

    private void btn_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_8ActionPerformed
       String txt = btn_8.getText();
     
       lbl_input.setText( lbl_input.getText() + txt );
    }//GEN-LAST:event_btn_8ActionPerformed

    private void btn_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_9ActionPerformed
       String txt = btn_9.getText();
     
       lbl_input.setText( lbl_input.getText() + txt );
    }//GEN-LAST:event_btn_9ActionPerformed

    private void btn_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_5ActionPerformed
       String txt = btn_5.getText();
     
       lbl_input.setText( lbl_input.getText() + txt );
    }//GEN-LAST:event_btn_5ActionPerformed

    private void btn_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_6ActionPerformed
       String txt = btn_6.getText();
     
       lbl_input.setText( lbl_input.getText() + txt );
    }//GEN-LAST:event_btn_6ActionPerformed

    private void btn_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_4ActionPerformed
       String txt = btn_4.getText();
     
       lbl_input.setText( lbl_input.getText() + txt );
    }//GEN-LAST:event_btn_4ActionPerformed

    private void btn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_1ActionPerformed
       String txt = btn_1.getText();
               System.out.println("Bracketa: " + setupBrackets );

     
       lbl_input.setText( lbl_input.getText() + txt );
       
    }//GEN-LAST:event_btn_1ActionPerformed

    private void btn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_2ActionPerformed
       String txt = btn_2.getText();
     
       lbl_input.setText( lbl_input.getText() + txt );
    }//GEN-LAST:event_btn_2ActionPerformed

    private void btn_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_3ActionPerformed
       String txt = btn_3.getText();
     
       lbl_input.setText( lbl_input.getText() + txt );
    }//GEN-LAST:event_btn_3ActionPerformed

    private void btn_ceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ceActionPerformed
      lbl_input.setText( "" );
      lbl_output.setText( "" );
      operator_1 = operator_2 = 0;
      lbl_otherInfo.setText("");
    }//GEN-LAST:event_btn_ceActionPerformed

    private void btn_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_0ActionPerformed
       String txt = btn_0.getText();

       lbl_input.setText( lbl_input.getText() + txt );
    }//GEN-LAST:event_btn_0ActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed

        
        String txt = btn_add.getText();
                
        if( !lbl_output.getText().equals("") ) {

            lbl_input.setText( lbl_output.getText() + txt );
            lbl_output.setText("");
            
         }
         else {
            lbl_input.setText( lbl_input.getText() + txt );
            
         } 
        
        

        
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_subActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_subActionPerformed
        
        String txt = btn_sub.getText();
        
        if( !lbl_output.getText().equals("") ) {

            lbl_input.setText( lbl_output.getText() + txt );
            lbl_otherInfo.setText( lbl_otherInfo.getText() + txt );
            
         }
         else {
            lbl_input.setText( lbl_input.getText() + txt );
         } 
    }//GEN-LAST:event_btn_subActionPerformed

    private void btn_divActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_divActionPerformed
        
        String txt = btn_div.getText();
        
        if( !lbl_output.getText().equals("") ) {

            lbl_input.setText( lbl_output.getText() + txt );
            lbl_otherInfo.setText( lbl_otherInfo.getText() + txt );
            
         }
         else {
            lbl_input.setText( lbl_input.getText() + txt );
         } 
    }//GEN-LAST:event_btn_divActionPerformed

    private double calculation( StringBuilder str ) {
        int k;
        double op = 0;
        StringBuilder tmpString = new StringBuilder();
        
        if( str.indexOf("+") != -1 || str.indexOf("-") != -1 ) op = 0;
        else op = 1;
        
        for( k=0;k<=str.length() - 1 ; k++){
            switch( str.charAt(k) ) {
                case '+' : {
                       id_operation = 1;
                       tmpString.append( str.substring( 0, k) );
                       str.replace( 0, k+1, "");
                       op = op + Double.parseDouble( tmpString.toString() );
                       tmpString.delete( 0, tmpString.length() );
                       k=0;            
                    
                       break;
                    }
                case '-' :{
                       id_operation = 2;
                       tmpString.append( str.substring( 0, k) );
                       str.replace( 0, k+1, "");
                       op = Double.parseDouble( tmpString.toString() ) - op;
                       tmpString.delete( 0, tmpString.length() );
                       k=0;                                       

                       break;
                    }
                case '*' :{
                       id_operation = 3;
                       tmpString.append( str.substring( 0, k) );
                       str.replace( 0, k+1, "");
                       op = op * Double.parseDouble( tmpString.toString() );
                       tmpString.delete( 0, tmpString.length() );
                       k=0;                                       
                    
                       break;
                    }
                case '/' : {
                       id_operation = 4;
                       tmpString.append( str.substring( 0, k) );
                       str.replace( 0, k+1, "");
                       op = op * Double.parseDouble( tmpString.toString() );
                       tmpString.delete( 0, tmpString.length() );
                       k=0;                                       

                       break;
                    }
                    
                case '^' :{
                       tmpString.append( str.substring( 0, k) );
                       str.replace( 0, k+1, "");
                       op = Math.pow( Double.parseDouble( tmpString.toString() ), Double.parseDouble( str.toString() ) );
                       tmpString.delete( 0, tmpString.length() );
                       k=0;                                       

                       break;
                    }
                    
            }
           


        }

        if( id_operation == 1 ) { op = op + Double.parseDouble( str.toString() ); id_operation = -1; }
        else if ( id_operation == 2 ) {op = op - Double.parseDouble( str.toString() ); id_operation = -1;}
        else if ( id_operation == 3 ) {op = op * Double.parseDouble( str.toString() ); id_operation = -1;}
        else if ( id_operation == 4 ) {op = op / Double.parseDouble( str.toString() ); id_operation = -1;}

        return op;
    }
    
    private void btn_resActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resActionPerformed
        int j = 0;

        StringBuilder str = new StringBuilder( lbl_input.getText() );
        StringBuilder tmpString = new StringBuilder();
        
        
        System.out.println("Stringa: " + str );
        System.out.println("Lunghezza stringa: " + ( str.length() - 1 ) );



        if( str.indexOf("(") != -1 ) {
            while( str.indexOf("(") != -1 ) {
                j = str.indexOf("(");

                while( str.charAt(j) != ')' ) {
                    j++;
                }

                tmpString.append( str.substring( str.indexOf("(") + 1, j ) );
                str.replace( str.indexOf("("), j + 1, Double.valueOf( calculation(tmpString) ).toString() );
                System.out.println( str );
                tmpString.delete( 0, tmpString.length() );
            }
            
            lbl_output.setText( Double.valueOf( calculation( str ) ).toString() );
            
        } else {
            tmpString.append( str );
            lbl_output.setText( Double.valueOf( calculation(tmpString) ).toString() ); 
        }               

    }//GEN-LAST:event_btn_resActionPerformed

    private void btn_commaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_commaActionPerformed
       if( lbl_input.getText() != "") {
           lbl_input.setText( lbl_input.getText() + btn_comma.getText() );
       }
    }//GEN-LAST:event_btn_commaActionPerformed

    private void btn_delCharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delCharActionPerformed
        if( lbl_input.getText() != "" ) {
            lbl_input.setText( lbl_input.getText().substring( 0, lbl_input.getText().length()-1) );
        } 
    }//GEN-LAST:event_btn_delCharActionPerformed

    private void btn_sinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sinActionPerformed
        if( lbl_output.getText() == "" ) {
            if( lbl_input.getText() != "" ) {
                lbl_output.setText( Double.valueOf( Math.sin( Math.toRadians( Double.parseDouble( lbl_input.getText() ) )) ).toString() ); 
            }
        }
        else {
            String res = lbl_output.getText();
            if( lbl_input.getText() == "" ) {
                return;
            }
            lbl_output.setText( Double.valueOf( Math.sin( Math.toRadians( Double.parseDouble( lbl_output.getText() ) )) ).toString() ); 
            lbl_input.setText( res );
        } 
    }//GEN-LAST:event_btn_sinActionPerformed

    private void btn_cosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cosActionPerformed
        if( lbl_output.getText() == "" ) {
            if( lbl_input.getText() != "" ) {
                lbl_output.setText( Double.valueOf( Math.cos( Math.toRadians( Double.parseDouble( lbl_input.getText() ) )) ).toString() ); 
            }
        }
        else {
            String res = lbl_output.getText();
            if( lbl_input.getText() == "" ) {
                return;
            }
            lbl_output.setText( Double.valueOf( Math.cos( Math.toRadians( Double.parseDouble( lbl_output.getText() ) )) ).toString() ); 
            lbl_input.setText( res );
        } 
    }//GEN-LAST:event_btn_cosActionPerformed

    private void btn_tanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tanActionPerformed
        if( lbl_output.getText() == "" ) {
            if( lbl_input.getText() != "" ) {
                lbl_output.setText( Double.valueOf( Math.tan( Math.toRadians( Double.parseDouble( lbl_input.getText() ) )) ).toString() ); 
            }
        }
        else {
            String res = lbl_output.getText();
            if( lbl_input.getText() == "" ) {
                return;
            }
            lbl_output.setText( Double.valueOf( Math.tan( Math.toRadians( Double.parseDouble( lbl_output.getText() ) )) ).toString() ); 
            lbl_input.setText( res );
        } 
    }//GEN-LAST:event_btn_tanActionPerformed

    private void btn_quadratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quadratoActionPerformed
        if( !lbl_output.getText().equals("") ) {
             lbl_input.setText( lbl_output.getText() + btn_quadrato.getText() );
             lbl_output.setText("");
         }
         else {
            lbl_input.setText( lbl_input.getText() + btn_quadrato.getText() );
         }
    }//GEN-LAST:event_btn_quadratoActionPerformed

    private void btn_cuboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cuboActionPerformed
        if( !lbl_output.getText().equals("") ) {
             lbl_input.setText( lbl_output.getText() + btn_cubo.getText() );
             lbl_output.setText("");
         }
         else {
            lbl_input.setText( lbl_input.getText() + btn_cubo.getText() );
         }
    }//GEN-LAST:event_btn_cuboActionPerformed

    private void btn_elevazione_nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_elevazione_nActionPerformed
        if( !lbl_output.getText().equals("") ) {
             lbl_input.setText( lbl_output.getText() + "^" );
             lbl_output.setText("");
         }
         else {
            lbl_input.setText( lbl_input.getText() + "^" );
         }
    }//GEN-LAST:event_btn_elevazione_nActionPerformed

    private void btn_elevation1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_elevation1ActionPerformed
        if( !lbl_output.getText().equals("") ) {
             lbl_input.setText( lbl_output.getText() + "1/(" + lbl_output.getText() + "^1)" );
             lbl_output.setText("");
         }
         else {
             lbl_input.setText( "1/(" + lbl_input.getText() + "^1)" );
         }
    }//GEN-LAST:event_btn_elevation1ActionPerformed

    private void btn_radActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_radActionPerformed
        lbl_output.setText( Double.valueOf( Math.toRadians( Double.parseDouble( lbl_input.getText() ) )).toString() );
    }//GEN-LAST:event_btn_radActionPerformed

    private void btn_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modActionPerformed
        if( !lbl_output.getText().equals("") ) {
             lbl_input.setText( lbl_output.getText() + btn_mod.getText() );
             lbl_output.setText("");
         }
         else {
             lbl_input.setText( lbl_input.getText() + btn_mod.getText() );
         }
    }//GEN-LAST:event_btn_modActionPerformed

    private void btn_sqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sqrtActionPerformed
        if( !lbl_output.getText().equals("") ) {
             lbl_input.setText( lbl_output.getText()  );
         }
         else {
             lbl_input.setText( lbl_input.getText() );
         } 
        
         lbl_output.setText( Double.valueOf( Math.sqrt(Double.parseDouble( lbl_input.getText() ) ) ).toString() ); 

    }//GEN-LAST:event_btn_sqrtActionPerformed

    private void btn_brackets_openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_brackets_openActionPerformed
        String txt = btn_brackets_open.getText();
        
        setupBrackets = true;
        System.out.println("Brackets aperta: ");
        if( !lbl_output.getText().equals("") ) {
            lbl_input.setText( lbl_output.getText() + txt );
            
         }
         else {
      
            lbl_input.setText( lbl_input.getText() + txt );
         } 
       
    }//GEN-LAST:event_btn_brackets_openActionPerformed

    private void btn_brackets_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_brackets_closeActionPerformed
        
        String txt = btn_brackets_close.getText();

        
        if( !lbl_output.getText().equals("") ) {
            lbl_input.setText( lbl_output.getText() + txt );
         }
         else {
            lbl_input.setText( lbl_input.getText() + txt );
         } 

    }//GEN-LAST:event_btn_brackets_closeActionPerformed

    private void btn_mulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mulActionPerformed
        
        String txt = btn_mul.getText();
        
        if( !lbl_output.getText().equals("") ) {
            lbl_input.setText( lbl_output.getText() + txt );            
         }
         else {
            lbl_input.setText( lbl_input.getText() + txt );
         } 

    }//GEN-LAST:event_btn_mulActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_0;
    private javax.swing.JButton btn_1;
    private javax.swing.JButton btn_2;
    private javax.swing.JButton btn_3;
    private javax.swing.JButton btn_4;
    private javax.swing.JButton btn_5;
    private javax.swing.JButton btn_6;
    private javax.swing.JButton btn_7;
    private javax.swing.JButton btn_8;
    private javax.swing.JButton btn_9;
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_brackets_close;
    private javax.swing.JButton btn_brackets_open;
    private javax.swing.JButton btn_ce;
    private javax.swing.JButton btn_comma;
    private javax.swing.JButton btn_cos;
    private javax.swing.JButton btn_cubo;
    private javax.swing.JButton btn_delChar;
    private javax.swing.JButton btn_div;
    private javax.swing.JButton btn_elevation1;
    private javax.swing.JButton btn_elevazione_n;
    private javax.swing.JButton btn_mod;
    private javax.swing.JButton btn_mul;
    private javax.swing.JButton btn_quadrato;
    private javax.swing.JButton btn_rad;
    private javax.swing.JButton btn_res;
    private javax.swing.JButton btn_sin;
    private javax.swing.JButton btn_sqrt;
    private javax.swing.JButton btn_sub;
    private javax.swing.JButton btn_tan;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbl_input;
    private javax.swing.JLabel lbl_otherInfo;
    private javax.swing.JLabel lbl_output;
    // End of variables declaration//GEN-END:variables

    private String calculation(StringBuffer str) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }


 
}
